### ISSUE TITLE
It does not work with system clipboard. 

### ISSUE THREAD

**Issue by duytientran** [yazgoo/yank-history#1]
Additionally when you delete something, I expect it to be in the yank history

**Comment by yazgoo** [comment]
Would you like it to handle copy from the system clipboard or just be able to paste in system clipboard ?

**Comment by duytientran** [comment]
Hi. It would be great if you can do both. Thanks

Tien Tran
________________________________

**Comment by yazgoo** [comment]
Unfortunately I did not find a way to handle deletes in vim.
Under neovim the plugin does support it though.
I'm currently working on capturing the system clipboard, but it probably require to run a separated program.

**Comment by yazgoo** [comment]
Added linux clipboard monitor to the project, closing this, please reopen if it does not solve the issue for you
